version: '3.2'
services:
  api:
    image: node:latest
    container_name: project-api
    restart: always
    networks:
      - project-bridge
    ports:
      - 3000:3000
    command:
      - yarn
      - yarn start:dev
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
networks:
  project-bridge:
    driver: bridge
